language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: Jl9lYa0V4W9G8cB2GkkwXoJ5IoDd3cJnY8yxOMRGW/jjJgriNSG0VsVYi5A8g58Da5zxY5erVQVoUV+8zMxpiMKAmYxjS5/5gPhj0eTDTeJ4Lx8kyqrEd3ZAMz4H0LQ2dUU+SEdd0qDEqEUt5YW8R3sUm5xzzo/F4ic2vSg0965GZBinxdK4yBRP09L5R8v1UmEXrDw/ccY7cCeZOr6W1nExhbbBGCh7NKudOXOcZJZefHLhPz7YWU73CSjCxIEDeL47UHXiGFHHNo2WpfmjlZ512pMy+H2JNX3DjqJe5X0qFs6oo+7a3WiI7zw6+ymLgYAq8370CzR5ICbZprV/vTx61ngjQw32lrB22WdvDLIK57wSHdoKFMFC6AnoyxqAE1B1YrUE4extOCpkbcrSrUZ+Xa7F8YoxIAn56staZiENupHkKjRCf9HjCcP7LpT773PrOrEuTdr5xkQPYHuOmyJ0YtbwgO6xlJVRj8R4K96slRtj4HD2Z5pJSL2URhDqLf7Lfk/Rz0fzDPos8aD0eGW4mODYYfliBYA2rsPqLqW7m7HCmQ0zSTAQTuikPDAJ1Ggaiv/Ie/6w+IZQcUFkD2I2Iz/9EEBiVq/ir3S3nIiFbN9sRNlVO5dAzf7OJZdbsFk0IrMXVuK5wzPSnIvPygF59gHQPo/ySVVB/yfXENA=
